from __future__ import annotations

from .selection import (
    _build_forecasting_table_options,
    _canonicalize_source_tables,
    _history_window_year_span,
    _is_clean_source_table,
    _normalize_filter_value,
    _normalize_source_table_name,
    _resolve_forecasting_selection,
    _selected_source_table_notes,
    _selected_source_tables,
    _source_table_canonical_key,
    _source_table_deduplication_note,
    _table_selection_label,
    _unique_notes,
)
from .shaping import (
    _build_daily_history,
    _build_forecast_rows,
    _build_monthly_outlook,
    _build_option_catalog,
    _build_options,
    _build_weekday_profile,
    _build_weekly_outlook,
)
from .sources import (
    _build_temperature_quality,
    _collect_forecasting_inputs,
    _collect_forecasting_metadata,
    _load_table_metadata,
    _load_temperature_quality,
    _resolve_history_window_min_year,
    _temperature_quality_from_daily_history,
    _temperature_quality_from_daily_rows,
)
from .sql import (
    _FORECASTING_SQL_CACHE,
    _build_daily_aggregate_view_sql,
    _build_daily_history_sql,
    _build_materialized_scope_conditions,
    _build_option_catalog_sql,
    _build_options_from_counter,
    _build_scope_conditions,
    _build_sql_cache_key,
    _count_forecasting_records_sql,
    _daily_aggregate_view_exists,
    _daily_aggregate_view_name,
    _load_daily_history_rows,
    _load_forecasting_records,
    _load_option_counts,
    _load_scope_total_count,
    _materialized_view_suffix,
    clear_forecasting_sql_cache,
    prepare_forecasting_materialized_views,
)
